[phases.setup]
nixPkgs = [
  "nodejs_18",              # ✅ OK
  "chromium",               # ✅ OK
  "nss",                 # ✅ OK
  "atk",                    # ✅ OK
  "cups",                   # ✅ Corrigido de 'libcups'
  "mesa",                   # ✅ OK
  "alsa-lib",               # ✅ OK
  "pango",                  # ✅ OK
  "gtk3",                   # ✅ OK
  "libxshmfence",           # ✅ OK
  ]
[start]
cmd = "node chatbot-borzi.js"