[phases.setup]
nixPkgs = [
  "nodejs_18",
  "npm_9",
  "chromium",
  "libnss",
  "atk",
  "libcups",
  "mesa",
  "alsa-lib",
  "pango",
  "libXScrnSaver",
  "gtk3",
  "libxshmfence",
  "glu",
  "libgbm"
]

[start]
cmd = "node chatbot-borzi.js"