[phases.setup]
nixPkgs = [
  "nodejs_18",
  "npm",
  "libnss3",
  "atk",
  "atkbridge",
  "cups",
  "mesa",
  "alsa-lib",
  "pango",
  "libxss",
  "gtk3",
  "libxshmfence",
  "glu",
  "chromium"
]

[start]
cmd = "node chatbot-borzi.js"